name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install deps
        run: |
          sudo apt-get install valac libgee-0.8-dev libgtk-3-dev libcairo-dev
      - name: Compile example
        run: make compile
      - name: Run tests
        run: make test
