name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install deps
        run: |
          sudo apt-get install valac libgee-0.8-dev libgtk-3-dev libcairo-dev xvfb
          pip install meson
          pip install ninja
      - name: Build
        run: |
          meson build
          ninja -C build
      - name: Run tests
        run: meson test -C build --wrapper="xvfb-run --auto-servernum --server-num=1"